package model;
// Generated 06/03/2014 04:49:02 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Departamento generated by hbm2java
 */
@Entity
@Table(name="departamento"
    ,schema="public"
)
public class Departamento  implements java.io.Serializable {


     private int idDepartamento;
     private String nombreDepartamento;
     private String tipo;
     private Set empleadoDepartamentos = new HashSet(0);

    public Departamento() {
    }

	
    public Departamento(int idDepartamento, String nombreDepartamento, String tipo) {
        this.idDepartamento = idDepartamento;
        this.nombreDepartamento = nombreDepartamento;
        this.tipo = tipo;
    }
    public Departamento(int idDepartamento, String nombreDepartamento, String tipo, Set empleadoDepartamentos) {
       this.idDepartamento = idDepartamento;
       this.nombreDepartamento = nombreDepartamento;
       this.tipo = tipo;
       this.empleadoDepartamentos = empleadoDepartamentos;
    }
   
     @Id 

    
    @Column(name="id_departamento", unique=true, nullable=false)
    public int getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(int idDepartamento) {
        this.idDepartamento = idDepartamento;
    }

    
    @Column(name="nombre_departamento", nullable=false, length=150)
    public String getNombreDepartamento() {
        return this.nombreDepartamento;
    }
    
    public void setNombreDepartamento(String nombreDepartamento) {
        this.nombreDepartamento = nombreDepartamento;
    }

    
    @Column(name="tipo", nullable=false, length=100)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="departamento")
    public Set getEmpleadoDepartamentos() {
        return this.empleadoDepartamentos;
    }
    
    public void setEmpleadoDepartamentos(Set empleadoDepartamentos) {
        this.empleadoDepartamentos = empleadoDepartamentos;
    }




}


