package model;
// Generated 06/03/2014 04:49:02 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DocenteDetalles generated by hbm2java
 */
@Entity
@Table(name="docente_detalles"
    ,schema="public"
)
public class DocenteDetalles  implements java.io.Serializable {


     private DocenteDetallesId id;
     private Docentes docentes;
     private String detalle;
     private BigDecimal valorActualHoras;
     private short totalHorasQuincenal;
     private short totalHorasFaltas;
     private BigDecimal descuentoXFaltas;
     private BigDecimal anticipoQuincenal;
     private BigDecimal egresoAnticipoQuincenal;

    public DocenteDetalles() {
    }

	
    public DocenteDetalles(DocenteDetallesId id, Docentes docentes, BigDecimal valorActualHoras, short totalHorasQuincenal, short totalHorasFaltas, BigDecimal descuentoXFaltas, BigDecimal anticipoQuincenal, BigDecimal egresoAnticipoQuincenal) {
        this.id = id;
        this.docentes = docentes;
        this.valorActualHoras = valorActualHoras;
        this.totalHorasQuincenal = totalHorasQuincenal;
        this.totalHorasFaltas = totalHorasFaltas;
        this.descuentoXFaltas = descuentoXFaltas;
        this.anticipoQuincenal = anticipoQuincenal;
        this.egresoAnticipoQuincenal = egresoAnticipoQuincenal;
    }
    public DocenteDetalles(DocenteDetallesId id, Docentes docentes, String detalle, BigDecimal valorActualHoras, short totalHorasQuincenal, short totalHorasFaltas, BigDecimal descuentoXFaltas, BigDecimal anticipoQuincenal, BigDecimal egresoAnticipoQuincenal) {
       this.id = id;
       this.docentes = docentes;
       this.detalle = detalle;
       this.valorActualHoras = valorActualHoras;
       this.totalHorasQuincenal = totalHorasQuincenal;
       this.totalHorasFaltas = totalHorasFaltas;
       this.descuentoXFaltas = descuentoXFaltas;
       this.anticipoQuincenal = anticipoQuincenal;
       this.egresoAnticipoQuincenal = egresoAnticipoQuincenal;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="cedula", column=@Column(name="cedula", nullable=false, length=15) ), 
        @AttributeOverride(name="fechaPago", column=@Column(name="fecha_pago", nullable=false, length=13) ) } )
    public DocenteDetallesId getId() {
        return this.id;
    }
    
    public void setId(DocenteDetallesId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cedula", nullable=false, insertable=false, updatable=false)
    public Docentes getDocentes() {
        return this.docentes;
    }
    
    public void setDocentes(Docentes docentes) {
        this.docentes = docentes;
    }

    
    @Column(name="detalle", length=100)
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }

    
    @Column(name="valor_actual_horas", nullable=false, precision=8)
    public BigDecimal getValorActualHoras() {
        return this.valorActualHoras;
    }
    
    public void setValorActualHoras(BigDecimal valorActualHoras) {
        this.valorActualHoras = valorActualHoras;
    }

    
    @Column(name="total_horas_quincenal", nullable=false)
    public short getTotalHorasQuincenal() {
        return this.totalHorasQuincenal;
    }
    
    public void setTotalHorasQuincenal(short totalHorasQuincenal) {
        this.totalHorasQuincenal = totalHorasQuincenal;
    }

    
    @Column(name="total_horas_faltas", nullable=false)
    public short getTotalHorasFaltas() {
        return this.totalHorasFaltas;
    }
    
    public void setTotalHorasFaltas(short totalHorasFaltas) {
        this.totalHorasFaltas = totalHorasFaltas;
    }

    
    @Column(name="descuento_x_faltas", nullable=false, precision=8)
    public BigDecimal getDescuentoXFaltas() {
        return this.descuentoXFaltas;
    }
    
    public void setDescuentoXFaltas(BigDecimal descuentoXFaltas) {
        this.descuentoXFaltas = descuentoXFaltas;
    }

    
    @Column(name="anticipo_quincenal", nullable=false, precision=8)
    public BigDecimal getAnticipoQuincenal() {
        return this.anticipoQuincenal;
    }
    
    public void setAnticipoQuincenal(BigDecimal anticipoQuincenal) {
        this.anticipoQuincenal = anticipoQuincenal;
    }

    
    @Column(name="egreso_anticipo_quincenal", nullable=false, precision=8)
    public BigDecimal getEgresoAnticipoQuincenal() {
        return this.egresoAnticipoQuincenal;
    }
    
    public void setEgresoAnticipoQuincenal(BigDecimal egresoAnticipoQuincenal) {
        this.egresoAnticipoQuincenal = egresoAnticipoQuincenal;
    }




}


