package model;
// Generated 06/03/2014 04:49:02 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Docentes generated by hbm2java
 */
@Entity
@Table(name="docentes"
    ,schema="public"
)
public class Docentes  implements java.io.Serializable {


     private String cedula;
     private Empleado empleado;
     private String facultad;
     private Date fechaDesafilacion;
     private boolean estado;
     private Set docenteDetalleses = new HashSet(0);

    public Docentes() {
    }

	
    public Docentes(Empleado empleado, String facultad, boolean estado) {
        this.empleado = empleado;
        this.facultad = facultad;
        this.estado = estado;
    }
    public Docentes(Empleado empleado, String facultad, Date fechaDesafilacion, boolean estado, Set docenteDetalleses) {
       this.empleado = empleado;
       this.facultad = facultad;
       this.fechaDesafilacion = fechaDesafilacion;
       this.estado = estado;
       this.docenteDetalleses = docenteDetalleses;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="empleado"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="cedula", unique=true, nullable=false, length=15)
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }

    
    @Column(name="facultad", nullable=false, length=150)
    public String getFacultad() {
        return this.facultad;
    }
    
    public void setFacultad(String facultad) {
        this.facultad = facultad;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_desafilacion", length=13)
    public Date getFechaDesafilacion() {
        return this.fechaDesafilacion;
    }
    
    public void setFechaDesafilacion(Date fechaDesafilacion) {
        this.fechaDesafilacion = fechaDesafilacion;
    }

    
    @Column(name="estado", nullable=false)
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="docentes")
    public Set getDocenteDetalleses() {
        return this.docenteDetalleses;
    }
    
    public void setDocenteDetalleses(Set docenteDetalleses) {
        this.docenteDetalleses = docenteDetalleses;
    }




}


