package model;
// Generated 06/03/2014 04:49:02 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EmpleadoDepartamentoId generated by hbm2java
 */
@Embeddable
public class EmpleadoDepartamentoId  implements java.io.Serializable {


     private String cedula;
     private short idDepartamento;
     private boolean estado;

    public EmpleadoDepartamentoId() {
    }

    public EmpleadoDepartamentoId(String cedula, short idDepartamento, boolean estado) {
       this.cedula = cedula;
       this.idDepartamento = idDepartamento;
       this.estado = estado;
    }
   


    @Column(name="cedula", nullable=false, length=15)
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }


    @Column(name="id_departamento", nullable=false)
    public short getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(short idDepartamento) {
        this.idDepartamento = idDepartamento;
    }


    @Column(name="estado", nullable=false)
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EmpleadoDepartamentoId) ) return false;
		 EmpleadoDepartamentoId castOther = ( EmpleadoDepartamentoId ) other; 
         
		 return ( (this.getCedula()==castOther.getCedula()) || ( this.getCedula()!=null && castOther.getCedula()!=null && this.getCedula().equals(castOther.getCedula()) ) )
 && (this.getIdDepartamento()==castOther.getIdDepartamento())
 && (this.isEstado()==castOther.isEstado());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCedula() == null ? 0 : this.getCedula().hashCode() );
         result = 37 * result + this.getIdDepartamento();
         result = 37 * result + (this.isEstado()?1:0);
         return result;
   }   


}


