package model;
// Generated 06/03/2014 04:49:02 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Empleado generated by hbm2java
 */
@Entity
@Table(name="empleado"
    ,schema="public"
)
public class Empleado  implements java.io.Serializable {


     private String cedula;
     private String nombres;
     private String apellidos;
     private String numCuenta;
     private String tipoCuenta;
     private Integer banco;
     private String email;
     private Docentes docentes;
     private Set observacions = new HashSet(0);
     private Set xlsresultados = new HashSet(0);
     private Funcion funcion;
     private Set empleadoDepartamentos = new HashSet(0);

    public Empleado() {
    }

	
    public Empleado(String cedula, String nombres, String apellidos) {
        this.cedula = cedula;
        this.nombres = nombres;
        this.apellidos = apellidos;
    }
    public Empleado(String cedula, String nombres, String apellidos, String numCuenta, String tipoCuenta, Integer banco, String email, Docentes docentes, Set observacions, Set xlsresultados, Funcion funcion, Set empleadoDepartamentos) {
       this.cedula = cedula;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.numCuenta = numCuenta;
       this.tipoCuenta = tipoCuenta;
       this.banco = banco;
       this.email = email;
       this.docentes = docentes;
       this.observacions = observacions;
       this.xlsresultados = xlsresultados;
       this.funcion = funcion;
       this.empleadoDepartamentos = empleadoDepartamentos;
    }
   
     @Id 

    
    @Column(name="cedula", unique=true, nullable=false, length=15)
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }

    
    @Column(name="nombres", nullable=false, length=150)
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    
    @Column(name="apellidos", nullable=false, length=150)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    
    @Column(name="num_cuenta", length=10)
    public String getNumCuenta() {
        return this.numCuenta;
    }
    
    public void setNumCuenta(String numCuenta) {
        this.numCuenta = numCuenta;
    }

    
    @Column(name="tipo_cuenta", length=2)
    public String getTipoCuenta() {
        return this.tipoCuenta;
    }
    
    public void setTipoCuenta(String tipoCuenta) {
        this.tipoCuenta = tipoCuenta;
    }

    
    @Column(name="banco")
    public Integer getBanco() {
        return this.banco;
    }
    
    public void setBanco(Integer banco) {
        this.banco = banco;
    }

    
    @Column(name="email", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="empleado")
    public Docentes getDocentes() {
        return this.docentes;
    }
    
    public void setDocentes(Docentes docentes) {
        this.docentes = docentes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empleado")
    public Set getObservacions() {
        return this.observacions;
    }
    
    public void setObservacions(Set observacions) {
        this.observacions = observacions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empleado")
    public Set getXlsresultados() {
        return this.xlsresultados;
    }
    
    public void setXlsresultados(Set xlsresultados) {
        this.xlsresultados = xlsresultados;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="empleado")
    public Funcion getFuncion() {
        return this.funcion;
    }
    
    public void setFuncion(Funcion funcion) {
        this.funcion = funcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empleado")
    public Set getEmpleadoDepartamentos() {
        return this.empleadoDepartamentos;
    }
    
    public void setEmpleadoDepartamentos(Set empleadoDepartamentos) {
        this.empleadoDepartamentos = empleadoDepartamentos;
    }




}


