package model;
// Generated 06/03/2014 04:49:02 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ObservacionId generated by hbm2java
 */
@Embeddable
public class ObservacionId  implements java.io.Serializable {


     private String cedula;
     private Date fechaPago;

    public ObservacionId() {
    }

    public ObservacionId(String cedula, Date fechaPago) {
       this.cedula = cedula;
       this.fechaPago = fechaPago;
    }
   


    @Column(name="cedula", nullable=false, length=15)
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }


    @Column(name="fecha_pago", nullable=false, length=29)
    public Date getFechaPago() {
        return this.fechaPago;
    }
    
    public void setFechaPago(Date fechaPago) {
        this.fechaPago = fechaPago;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ObservacionId) ) return false;
		 ObservacionId castOther = ( ObservacionId ) other; 
         
		 return ( (this.getCedula()==castOther.getCedula()) || ( this.getCedula()!=null && castOther.getCedula()!=null && this.getCedula().equals(castOther.getCedula()) ) )
 && ( (this.getFechaPago()==castOther.getFechaPago()) || ( this.getFechaPago()!=null && castOther.getFechaPago()!=null && this.getFechaPago().equals(castOther.getFechaPago()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCedula() == null ? 0 : this.getCedula().hashCode() );
         result = 37 * result + ( getFechaPago() == null ? 0 : this.getFechaPago().hashCode() );
         return result;
   }   


}


