package model;
// Generated 06/03/2014 04:49:02 PM by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Observacion generated by hbm2java
 */
@Entity
@Table(name="observacion"
    ,schema="public"
)
public class Observacion  implements java.io.Serializable {


     private ObservacionId id;
     private Empleado empleado;
     private short idDepartamento;
     private String observacionTxt;

    public Observacion() {
    }

	
    public Observacion(ObservacionId id, Empleado empleado, short idDepartamento) {
        this.id = id;
        this.empleado = empleado;
        this.idDepartamento = idDepartamento;
    }
    public Observacion(ObservacionId id, Empleado empleado, short idDepartamento, String observacionTxt) {
       this.id = id;
       this.empleado = empleado;
       this.idDepartamento = idDepartamento;
       this.observacionTxt = observacionTxt;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="cedula", column=@Column(name="cedula", nullable=false, length=15) ), 
        @AttributeOverride(name="fechaPago", column=@Column(name="fecha_pago", nullable=false, length=29) ) } )
    public ObservacionId getId() {
        return this.id;
    }
    
    public void setId(ObservacionId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cedula", nullable=false, insertable=false, updatable=false)
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }

    
    @Column(name="id_departamento", nullable=false)
    public short getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(short idDepartamento) {
        this.idDepartamento = idDepartamento;
    }

    
    @Column(name="observacion_txt")
    public String getObservacionTxt() {
        return this.observacionTxt;
    }
    
    public void setObservacionTxt(String observacionTxt) {
        this.observacionTxt = observacionTxt;
    }




}


