package model;
// Generated 06/03/2014 04:49:02 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Quincena generated by hbm2java
 */
@Entity
@Table(name="quincena"
    ,schema="public"
)
public class Quincena  implements java.io.Serializable {


     private QuincenaId id;
     private EmpleadoDepartamento empleadoDepartamento;
     private Rubro rubro;
     private BigDecimal valorRubro;
     private char tipoPago;

    public Quincena() {
    }

    public Quincena(QuincenaId id, EmpleadoDepartamento empleadoDepartamento, Rubro rubro, BigDecimal valorRubro, char tipoPago) {
       this.id = id;
       this.empleadoDepartamento = empleadoDepartamento;
       this.rubro = rubro;
       this.valorRubro = valorRubro;
       this.tipoPago = tipoPago;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="cedula", column=@Column(name="cedula", nullable=false, length=15) ), 
        @AttributeOverride(name="idDepartamento", column=@Column(name="id_departamento", nullable=false) ), 
        @AttributeOverride(name="idRubro", column=@Column(name="id_rubro", nullable=false) ), 
        @AttributeOverride(name="fechaPago", column=@Column(name="fecha_pago", nullable=false, length=29) ) } )
    public QuincenaId getId() {
        return this.id;
    }
    
    public void setId(QuincenaId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="cedula", referencedColumnName="cedula", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="id_departamento", referencedColumnName="id_departamento", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="estado", referencedColumnName="estado", nullable=false, insertable=false, updatable=false) } )
    public EmpleadoDepartamento getEmpleadoDepartamento() {
        return this.empleadoDepartamento;
    }
    
    public void setEmpleadoDepartamento(EmpleadoDepartamento empleadoDepartamento) {
        this.empleadoDepartamento = empleadoDepartamento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_rubro", nullable=false, insertable=false, updatable=false)
    public Rubro getRubro() {
        return this.rubro;
    }
    
    public void setRubro(Rubro rubro) {
        this.rubro = rubro;
    }

    
    @Column(name="valor_rubro", nullable=false, precision=8)
    public BigDecimal getValorRubro() {
        return this.valorRubro;
    }
    
    public void setValorRubro(BigDecimal valorRubro) {
        this.valorRubro = valorRubro;
    }

    
    @Column(name="tipo_pago", nullable=false, length=1)
    public char getTipoPago() {
        return this.tipoPago;
    }
    
    public void setTipoPago(char tipoPago) {
        this.tipoPago = tipoPago;
    }




}


