package model;
// Generated 06/03/2014 04:49:02 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Rubro generated by hbm2java
 */
@Entity
@Table(name="rubro"
    ,schema="public"
)
public class Rubro  implements java.io.Serializable {


     private int idRubro;
     private String nombre;
     private String tipo;
     private Set quincenas = new HashSet(0);

    public Rubro() {
    }

	
    public Rubro(int idRubro, String nombre, String tipo) {
        this.idRubro = idRubro;
        this.nombre = nombre;
        this.tipo = tipo;
    }
    public Rubro(int idRubro, String nombre, String tipo, Set quincenas) {
       this.idRubro = idRubro;
       this.nombre = nombre;
       this.tipo = tipo;
       this.quincenas = quincenas;
    }
   
     @Id 

    
    @Column(name="id_rubro", unique=true, nullable=false)
    public int getIdRubro() {
        return this.idRubro;
    }
    
    public void setIdRubro(int idRubro) {
        this.idRubro = idRubro;
    }

    
    @Column(name="nombre", nullable=false, length=120)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="tipo", nullable=false, length=10)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rubro")
    public Set getQuincenas() {
        return this.quincenas;
    }
    
    public void setQuincenas(Set quincenas) {
        this.quincenas = quincenas;
    }




}


