package model;
// Generated 06/03/2014 04:49:02 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Temporal;

/**
 * XlsresultadoId generated by hbm2java
 */
@Embeddable
public class XlsresultadoId  implements java.io.Serializable {


     private String cedula;
     private Date fechapago;

    public XlsresultadoId() {
    }

    public XlsresultadoId(String cedula, Date fechapago) {
       this.cedula = cedula;
       this.fechapago = fechapago;
    }
   


    @Column(name="cedula", nullable=false, length=15)
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }


    @Column(name="fechapago", nullable=false, length=13)   
    public Date getFechapago() {
        return this.fechapago;
    }
    
    public void setFechapago(Date fechapago) {
        this.fechapago = fechapago;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof XlsresultadoId) ) return false;
		 XlsresultadoId castOther = ( XlsresultadoId ) other; 
         
		 return ( (this.getCedula()==castOther.getCedula()) || ( this.getCedula()!=null && castOther.getCedula()!=null && this.getCedula().equals(castOther.getCedula()) ) )
 && ( (this.getFechapago()==castOther.getFechapago()) || ( this.getFechapago()!=null && castOther.getFechapago()!=null && this.getFechapago().equals(castOther.getFechapago()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCedula() == null ? 0 : this.getCedula().hashCode() );
         result = 37 * result + ( getFechapago() == null ? 0 : this.getFechapago().hashCode() );
         return result;
   }   


}


